name: run fixa test

on:
  workflow_call:
    inputs:
      agent_id:
        required: true
        type: string
        description: The agent ID of the agent to run the test on
      scenario_ids:
        type: string
        description: The scenario IDs to run the test on, separated by commas. Don't provide this if you want to run the test on all scenarios.
      persona_ids:
        type: string
        description: The persona IDs to run the test on, separated by commas. Don't provide this if you want to run the test with all personas.
      time_limit:
        type: number
        description: The time limit for the test in minutes. Defaults to 10 minutes.
        default: 10
    secrets:
      FIXA_API_KEY:
        required: true

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fixa-ci repository
        uses: actions/checkout@v4
        with:
          repository: fixadev/fixa-ci
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: node run-test.js
        env:
          FIXA_API_KEY: ${{ secrets.FIXA_API_KEY }}
          AGENT_ID: ${{ inputs.agent_id }}
          SCENARIO_IDS: ${{ inputs.scenario_ids }}
          PERSONA_IDS: ${{ inputs.persona_ids }}
          TIME_LIMIT: ${{ inputs.time_limit }}
