name: test run-test workflow

on:
  workflow_dispatch:
    inputs:
      agent_id:
        description: "Agent ID to test"
        required: true
        type: string
      scenario_ids:
        description: "Scenario IDs (comma-separated)"
        required: false
        type: string
      persona_ids:
        description: "Persona IDs (comma-separated)"
        required: false
        type: string

jobs:
  call-test-workflow:
    uses: ./.github/workflows/run-test.yml
    with:
      agent_id: ${{ inputs.agent_id }}
      scenario_ids: ${{ inputs.scenario_ids }}
      persona_ids: ${{ inputs.persona_ids }}
    secrets: inherit
